# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  group: kconfig

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    perl_line.sh {'some':'data'}
    ./repl.sh
  displayName: 'test and replacet'

- script: |
    echo $(kconfig-p1.b64) > kconfig.b64
    echo $(kconfig-p2.b64) >> kconfig.b64
    echo $(kconfig-p3.b64) >> kconfig.b64
    echo $(kconfig-p4.b64) >> kconfig.b64
    cat kconfig.b64 | base64 --decode > ~/.kube/config
  displayName: 'list files'

- task: KubectlInstaller@0
  inputs:
    kubectlVersion: 'latest'

- task: Kubernetes@1
  inputs:
    connectionType: 'None'
    namespace: 'default'
    command: 'get'
    arguments: 'pods'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'